apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: upsilon-workshop
  annotations:
    version: v1.0.0
    description: "Upsilon Workshop API Server"
spec:
  components:
    - name: django # Workshop API Server
      type: webservice
      properties:
        image: yayacout/upsilon-workshop
        cpu: "0.25"
        memory: "950Mi"
        ports:
        - port: 8000
          expose: true

      traits:
      - type: napptive-ingress # Expose port 80 (workshop API server) to the internet
        properties:
          name: django
          port: 8000
          path: /
      - type: cpuscaler # Automatically scale up/down based on CPU usage
      - type: scaler # Allow scaling (we use 2 replicas in case of a crash of one of the pods)
        properties:
          replicas: 2

      # Secret configuration
      - type: storage
        properties:
          secret:
            - name: mysql-config
              mountOnly: true # Crash if secret is not found
              mountPath: /etc/workshop/mysql-config
              # Mount Secret to Env
              mountToEnvs:
              - envName: MYSQL_HOST
                secretKey: host
              - envName: MYSQL_PORT
                secretKey: port
              - envName: MYSQL_USER
                secretKey: user
              - envName: MYSQL_PASSWORD
                secretKey: password
              - envName: MYSQL_DB
                secretKey: db
              - envName: DJANGO_SECRET_KEY
                secretKey: django_secret_key
