"""
Django settings for workshop project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""


from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# If DJANGO_SECURITY_KEY environnement variable is set, use it
SECRET_KEY = (
    os.environ.get("DJANGO_SECURITY_KEY")
    or "django-insecure-!flkdn#38kmet0pqxwy_t^1v1)j=46i!ye=zgsdzzy5qgyb#n^"
)
# SECURITY WARNING: don't run with debug turned on in production!
# If DEPLOY=1 environnement flag is set, use DEBUG=False
DEBUG = os.environ.get("DEPLOY") != "1"
ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admindocs",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    'rest_framework',
    'knox',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    'workshop'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "workshop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "workshop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# If DEPLOY=1 environnement flag is set, use MySQL database
if os.environ.get("DEPLOY") == "1":
    # If MYSQL_HOST, MYSQL_PORT, MYSQL_USER and MYSQL_PASSWORD environnement
    # variables are set, use them to connect to the database
    if all(
        os.environ.get(var)
        for var in ["MYSQL_HOST", "MYSQL_PORT", "MYSQL_USER", "MYSQL_PASSWORD",
                    "MYSQL_DB"]
    ):
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "NAME": os.environ.get("MYSQL_DB"),
                "HOST": os.environ.get("MYSQL_HOST"),
                "PORT": os.environ.get("MYSQL_PORT"),
                "USER": os.environ.get("MYSQL_USER"),
                "PASSWORD": os.environ.get("MYSQL_PASSWORD"),
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "NAME": "workshop",
                "OPTIONS": {
                    "read_default_file": os.path.join(BASE_DIR, "mysql.cnf"),
                },
            }
        }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

# CSRF trusted origins (endpoint url for the API and the frontend)
CSRF_TRUSTED_ORIGINS = [
    "https://django-cdqivkhudi9mmk5gqgb0.apps.playground.napptive.dev"
]
CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'knox.auth.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}

# Knox settings (set the user serializer to use)
REST_KNOX = {
    'USER_SERIALIZER': 'knox.serializers.UserSerializer'
}

# Spectacular settings (for the API documentation)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Upsilon Workshop API',
    'DESCRIPTION': 'API for the Upsilon Workshop',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS settings
CORS_ORIGIN_REGEX_WHITELIST = [
    r"http(?s)://(?:(?:127|0)\.0\.0\.(?:0|1)|localhost):3000",
    r"http(?s)://(?:(?:127|0)\.0\.0\.(?:0|1)|localhost):5173",
]
