# Generated by Django 4.1.1 on 2023-01-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="script",
            name="tags",
            field=models.ManyToManyField(blank=True, to="workshop.tag"),
        ),
    ]
