# Generated by Django 4.2.1 on 2023-06-11 12:18

from django.db import migrations, models
import workshop.api.validators


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="script",
            old_name="description",
            new_name="short_description",
        ),
        migrations.AlterField(
            model_name="script",
            name="licence",
            field=models.CharField(default="Unspecified", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/+/-/_ only.",
                max_length=150,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[workshop.api.validators.URLUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
