# Generated by Django 4.2.1 on 2023-06-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0002_rename_description_script_short_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="long_description",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="script",
            name="short_description",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
