# Generated by Django 4.1.1 on 2023-01-24 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workshop", "0003_script_collaborators_alter_script_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="script",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scripts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="collaborations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
