# Generated by Django 4.2.1 on 2023-10-04 12:42

from django.db import migrations, models
import workshop.api.validators


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0003_script_long_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="runner",
            field=models.CharField(
                default="default",
                max_length=100,
                validators=[workshop.api.validators.validate_runner],
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="long_description",
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
