# Generated by Django 4.2.1 on 2023-12-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0004_script_runner_alter_script_long_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="warning_private_project",
            field=models.BooleanField(
                default=False,
                help_text="This field specify wether the user should be informed about the existence of the private projects",
            ),
        ),
    ]
