# Generated by Django 4.1.1 on 2023-01-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_alter_script_author_alter_script_collaborators"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
