# Generated by Django 5.1.6 on 2025-02-11 11:29

import uuid
import workshop.api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_user_warning_private_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=workshop.api.models.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=workshop.api.models.Char32UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
