# Generated by Django 5.1.6 on 2025-02-11 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_alter_rating_id_alter_script_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
