# Generated by Django 5.1.6 on 2025-08-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_alter_rating_id_alter_script_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='is_unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
